### ISSUE TITLE
[Player] Ska man kunna Dasha på marken.

### ISSUE THREAD

**Issue by Knase23** [Taxmannen/In-Heaven#114]
Som vi har det just nu i spelet, så kan du dasha om du står på marken. 

I designdokumentet står det att man behöver vara i luften för att kunna använda Dash.

**Comment by chritaq** [comment]
Ja, man ska kunna dasha på marken. Det om luften är hur dashen fungerar i luften, då det fungerar lite annorlunda i luften än på marken.
När man är i luften ska man inte kunna dasha mer än en gång.
