### ISSUE TITLE
[Planning] Lägg upp board för Design-frågor. Vi i design har en del frågor som kommer upp under projektet. Så skulle varit bra med en board för detta så man även samlar dessa här och lösa dem.

### ISSUE THREAD

**Issue by chritaq** [Taxmannen/In-Heaven#58]

**Comment by Knase23** [comment]
Har nu gjort nu ett Project board, som är för Er Designers om ni har frågor till varandra. En bra grej kan vara att skriva svaren på frågorna , som kommentar på frågan.

Project bordet heter: " Design - Question" 

@chritaq @Sjupp @Taxmannen
