### ISSUE TITLE
FeedBack: You can use Dash/SledgeHammer(Parry)

### ISSUE THREAD

**Issue by Knase23** [Taxmannen/In-Heaven#96]
How do the player know its ability is on cooldown? When is it available for use?

UI?
Effects?

**Comment by chritaq** [comment]
Dash:
- Vi snor ett upplägg som smash använder när man inte kan attackera mer i luften. Karaktären börjar flasha lätt. Detta bör räcka och inte vara alltför distraherande. Se designdokumentet för mer detaljer. https://docs.google.com/document/d/1gWMe4xrEdVTxn8N6Lvjw-BUkVnKcsiZUwnv4Qmr1WUU/edit#

Sledgehammer:
- Cooldownen kommer vara väldigt kort, så antagligen kommer det inte behövas något visuellt.
