### ISSUE TITLE
FeedBack: Better explanation for Sledge Hammer.

### ISSUE THREAD

**Issue by Knase23** [Taxmannen/In-Heaven#99]
Need more explanation for what the sledge hammers use is?

Only for parrying?
Able to hit the boss if a part of it is really near the player? Example: A hand smash down where the player last was. The hand becomes a weakpoint to swing the hammer for MORE damage then shooting it?

**Comment by chritaq** [comment]
Right now, it'll only be for parrying. 
Worth adding it as an attack in "Features" though.
